baseurl = "https://www.sandersdenardi.com/"
title = "Sanders DeNardi"
languageCode = "en-US"
theme = "hyde-x"
pygmentsuseclasses = true
paginate = 10

[author]
    name = "Sanders DeNardi"

[taxonomies]
    category = "categories"

[params]
    truncate = true
    hideReadingTime = true
    hideCopyright = true
    theme = "theme-base-00"
    highlight = "solarized_dark"
    hideHome = true
    googleAnalytics = "UA-43803722-1"
    ogImageUrl = "twitter-card.jpg"

    # Sidebar social links
    github = "sedenardi"
    twitter = "srednass"
    email = "sandersdenardi@gmail.com"

[[menu.main]]
    url = "/about"
    Name = "About"

[[menu.main]]
    Name = "Projects"

[[menu.main]]
    parent = "Projects"
    Name = "Scaffmap"
    url = "https://www.sprinkmap.com/scaff"
    weight = 1

[[menu.main]]
    parent = "Projects"
    Name = "Vibe Vault"
    url = "https://play.google.com/store/apps/details?id=com.code.vibevault"
    weight = 2

[[menu.main]]
    parent = "Projects"
    Name = "Central Walk"
    url = "https://www.sandersdenardi.com/projects/central-walk/"
    weight = 3

[[menu.main]]
    parent = "Projects"
    Name = "SVUViz"
    url = "https://svuviz.sandersdenardi.com/"
    weight = 4

[[menu.main]]
    parent = "Projects"
    Name = "Festival Guide"
    url = "https://www.sandersdenardi.com/projects/festival-guide/"
    weight = 5

[[menu.main]]
    parent = "Projects"
    Name = "Score Tweets"
    url = "https://github.com/sedenardi/score-tweets"
    weight = 6

[[menu.main]]
    parent = "Projects"
    Name = "E-bike"
    url = "https://www.sandersdenardi.com/ebike/"
    weight = 7

[[menu.main]]
    parent = "Projects"
    Name = "All Projects"
    url = "https://www.sandersdenardi.com/projects/"
    weight = 8
